---
# tasks file for common
  become: true
  become_method: sudo
  become_user: dry

- name: include OS related var files
  include_vars: "{{ ansible_os_family }}_vars.yml"

- name: include OS sepcific common tasks
  include: "{{ ansible_os_family }}_setup.yml"